#!/bin/sh

# Make sure you're in the root Compojure dir
cd `dirname $0`

for file in `find deps -name *.jar`; do
    jars=$jars:$file
done

classpath=app:$jars

options='-server'

if which rlwrap > /dev/null; then
   rlwrap=rlwrap
else
   rlwrap=
fi

if [ $# -gt 0 ]; then
   $rlwrap java $options -cp $classpath clojure.main -i boot.clj --repl 
else
   java $options -cp $classpath clojure.main boot.clj
fi

