#!/bin/sh
; Make sure you're in the root Compojure dir
cd `dirname $0`; cd ..

for file in jars/*.jar; do
    jars=$jars:$file
done

classpath=app:$jars:lib

java -cp $classpath clojure.lang.Script boot/boot.clj
